name: Build and Deploy Godot HTML5

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Godot
        uses: firebelley/setup-godot@v2
        with:
          godot-version: 4.4
          export-templates: true

      - name: Export project to HTML5
        run: |
          mkdir -p build/web
          godot --headless --export-release "HTML5" build/web/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
          publish_branch: gh-pages
